export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"
export const AUTH_ERROR = "AUTH_ERROR"
export const USER_LOAD = "USER_LOAD"
export const CLEAR_ERRORS = "USER_LOADED"
export const GET_USER = "GET_USER"
